// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tendermint/nymabci/transaction/proto/types.proto

package transaction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	scheme "github.com/nymtech/nym/crypto/coconut/scheme"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewAccountRequest struct {
	// Public Key of the user used to derive account address and validate signature
	Address []byte `protobuf:"bytes,1,opt,name=Address,json=address,proto3" json:"Address,omitempty"`
	// represents some optional credential from an IP if required
	Credential []byte `protobuf:"bytes,2,opt,name=Credential,json=credential,proto3" json:"Credential,omitempty"`
	// Signature on request to confirm its validity + asserts knowledge of private key
	Sig                  []byte   `protobuf:"bytes,3,opt,name=Sig,json=sig,proto3" json:"Sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAccountRequest) Reset()         { *m = NewAccountRequest{} }
func (m *NewAccountRequest) String() string { return proto.CompactTextString(m) }
func (*NewAccountRequest) ProtoMessage()    {}
func (*NewAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb862c5130efc92, []int{0}
}

func (m *NewAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAccountRequest.Unmarshal(m, b)
}
func (m *NewAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAccountRequest.Marshal(b, m, deterministic)
}
func (m *NewAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAccountRequest.Merge(m, src)
}
func (m *NewAccountRequest) XXX_Size() int {
	return xxx_messageInfo_NewAccountRequest.Size(m)
}
func (m *NewAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewAccountRequest proto.InternalMessageInfo

func (m *NewAccountRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *NewAccountRequest) GetCredential() []byte {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (m *NewAccountRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

// DEBUG
type AccountTransferRequest struct {
	// Used to validate signature + determine source address
	SourceAddress []byte `protobuf:"bytes,1,opt,name=SourceAddress,json=sourceAddress,proto3" json:"SourceAddress,omitempty"`
	// Used to determine target address
	TargetAddress []byte `protobuf:"bytes,2,opt,name=TargetAddress,json=targetAddress,proto3" json:"TargetAddress,omitempty"`
	// Amount to be transferred
	Amount uint64 `protobuf:"varint,3,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	// While this function will only be available in debug and hence a nonce is really not needed,
	// I figured I should include it anyway as it's a good practice + will need to figure out a proper
	// nonce system anyway.
	Nonce []byte `protobuf:"bytes,4,opt,name=Nonce,json=nonce,proto3" json:"Nonce,omitempty"`
	// Signature on request to confirm its validitiy
	Sig                  []byte   `protobuf:"bytes,5,opt,name=Sig,json=sig,proto3" json:"Sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountTransferRequest) Reset()         { *m = AccountTransferRequest{} }
func (m *AccountTransferRequest) String() string { return proto.CompactTextString(m) }
func (*AccountTransferRequest) ProtoMessage()    {}
func (*AccountTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb862c5130efc92, []int{1}
}

func (m *AccountTransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountTransferRequest.Unmarshal(m, b)
}
func (m *AccountTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountTransferRequest.Marshal(b, m, deterministic)
}
func (m *AccountTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountTransferRequest.Merge(m, src)
}
func (m *AccountTransferRequest) XXX_Size() int {
	return xxx_messageInfo_AccountTransferRequest.Size(m)
}
func (m *AccountTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountTransferRequest proto.InternalMessageInfo

func (m *AccountTransferRequest) GetSourceAddress() []byte {
	if m != nil {
		return m.SourceAddress
	}
	return nil
}

func (m *AccountTransferRequest) GetTargetAddress() []byte {
	if m != nil {
		return m.TargetAddress
	}
	return nil
}

func (m *AccountTransferRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AccountTransferRequest) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *AccountTransferRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type DepositCoconutCredentialRequest struct {
	// The actual credential
	Sig *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=Sig,json=sig,proto3" json:"Sig,omitempty"`
	// The public attributes in credential. Note that pubM[0] = BIG(value)
	PubM [][]byte `protobuf:"bytes,2,rep,name=PubM,json=pubM,proto3" json:"PubM,omitempty"`
	// Crypto materials to verify the credential + required NIZK
	Theta *scheme.ProtoThetaTumbler `protobuf:"bytes,3,opt,name=Theta,json=theta,proto3" json:"Theta,omitempty"`
	// Value of the credential. While it is included in a BIG form in CryptoMaterials, it's easier to operate on it
	// when it's an int. We can't send it as an uint64, as milagro requires a normal int argument to construct a BIG num.
	Value int64 `protobuf:"varint,4,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	// Address of the service provider to which the proof is bound and whose account balance will be increased
	ProviderAddress      []byte   `protobuf:"bytes,5,opt,name=ProviderAddress,json=providerAddress,proto3" json:"ProviderAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositCoconutCredentialRequest) Reset()         { *m = DepositCoconutCredentialRequest{} }
func (m *DepositCoconutCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*DepositCoconutCredentialRequest) ProtoMessage()    {}
func (*DepositCoconutCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb862c5130efc92, []int{2}
}

func (m *DepositCoconutCredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositCoconutCredentialRequest.Unmarshal(m, b)
}
func (m *DepositCoconutCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositCoconutCredentialRequest.Marshal(b, m, deterministic)
}
func (m *DepositCoconutCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositCoconutCredentialRequest.Merge(m, src)
}
func (m *DepositCoconutCredentialRequest) XXX_Size() int {
	return xxx_messageInfo_DepositCoconutCredentialRequest.Size(m)
}
func (m *DepositCoconutCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositCoconutCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositCoconutCredentialRequest proto.InternalMessageInfo

func (m *DepositCoconutCredentialRequest) GetSig() *scheme.ProtoSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *DepositCoconutCredentialRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

func (m *DepositCoconutCredentialRequest) GetTheta() *scheme.ProtoThetaTumbler {
	if m != nil {
		return m.Theta
	}
	return nil
}

func (m *DepositCoconutCredentialRequest) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *DepositCoconutCredentialRequest) GetProviderAddress() []byte {
	if m != nil {
		return m.ProviderAddress
	}
	return nil
}

type TransferToPipeAccountNotification struct {
	// Used to identify the particular watcher and to verify signature
	WatcherPublicKey []byte `protobuf:"bytes,1,opt,name=WatcherPublicKey,json=watcherPublicKey,proto3" json:"WatcherPublicKey,omitempty"`
	// Ethereum address of the client
	ClientAddress []byte `protobuf:"bytes,2,opt,name=ClientAddress,json=clientAddress,proto3" json:"ClientAddress,omitempty"`
	// While right now it's completely unrequired as there is only a single pipe account, it might be useful
	// to have this information in the future if we decided to monitor multiple chains or have multiple pipe accounts
	// for example on epoch changes.
	PipeAccountAddress []byte `protobuf:"bytes,3,opt,name=PipeAccountAddress,json=pipeAccountAddress,proto3" json:"PipeAccountAddress,omitempty"`
	// Amount transferred by the client to the pipe account.
	Amount uint64 `protobuf:"varint,4,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	// Hash of the transaction in which the transfer occured.
	// Used to distinguish from multiple transfers the client might have done.
	TxHash []byte `protobuf:"bytes,5,opt,name=TxHash,json=txHash,proto3" json:"TxHash,omitempty"`
	// Signature on the entire message done with the watcher's key.
	Sig                  []byte   `protobuf:"bytes,6,opt,name=Sig,json=sig,proto3" json:"Sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferToPipeAccountNotification) Reset()         { *m = TransferToPipeAccountNotification{} }
func (m *TransferToPipeAccountNotification) String() string { return proto.CompactTextString(m) }
func (*TransferToPipeAccountNotification) ProtoMessage()    {}
func (*TransferToPipeAccountNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb862c5130efc92, []int{3}
}

func (m *TransferToPipeAccountNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferToPipeAccountNotification.Unmarshal(m, b)
}
func (m *TransferToPipeAccountNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferToPipeAccountNotification.Marshal(b, m, deterministic)
}
func (m *TransferToPipeAccountNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferToPipeAccountNotification.Merge(m, src)
}
func (m *TransferToPipeAccountNotification) XXX_Size() int {
	return xxx_messageInfo_TransferToPipeAccountNotification.Size(m)
}
func (m *TransferToPipeAccountNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferToPipeAccountNotification.DiscardUnknown(m)
}

var xxx_messageInfo_TransferToPipeAccountNotification proto.InternalMessageInfo

func (m *TransferToPipeAccountNotification) GetWatcherPublicKey() []byte {
	if m != nil {
		return m.WatcherPublicKey
	}
	return nil
}

func (m *TransferToPipeAccountNotification) GetClientAddress() []byte {
	if m != nil {
		return m.ClientAddress
	}
	return nil
}

func (m *TransferToPipeAccountNotification) GetPipeAccountAddress() []byte {
	if m != nil {
		return m.PipeAccountAddress
	}
	return nil
}

func (m *TransferToPipeAccountNotification) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransferToPipeAccountNotification) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *TransferToPipeAccountNotification) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type CredentialRequest struct {
	// Ethereum address of the client
	ClientAddress []byte `protobuf:"bytes,1,opt,name=ClientAddress,json=clientAddress,proto3" json:"ClientAddress,omitempty"`
	// While right now it's completely unrequired as there is only a single pipe account, it might be useful
	// to have this information in the future if we decided to monitor multiple chains or have multiple pipe accounts
	// for example on epoch changes.
	PipeAccountAddress []byte `protobuf:"bytes,2,opt,name=PipeAccountAddress,json=pipeAccountAddress,proto3" json:"PipeAccountAddress,omitempty"`
	// All the cryptographic materials required by issuers to perform a blind sign
	CryptoMaterials *scheme.ProtoBlindSignMaterials `protobuf:"bytes,3,opt,name=CryptoMaterials,json=cryptoMaterials,proto3" json:"CryptoMaterials,omitempty"`
	// Value of the credential. While it is included in a BIG form in CryptoMaterials, it's easier to operate on it
	// when it's an int. We can't send it as an uint64, as milagro requires a normal int argument to construct a BIG num.
	Value int64 `protobuf:"varint,4,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	// Required to prevent replay attacks.
	Nonce []byte `protobuf:"bytes,5,opt,name=Nonce,json=nonce,proto3" json:"Nonce,omitempty"`
	// Signature on entire request with client's ethereum key (so that client's address could be used to verify it)
	Sig                  []byte   `protobuf:"bytes,6,opt,name=Sig,json=sig,proto3" json:"Sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredentialRequest) Reset()         { *m = CredentialRequest{} }
func (m *CredentialRequest) String() string { return proto.CompactTextString(m) }
func (*CredentialRequest) ProtoMessage()    {}
func (*CredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb862c5130efc92, []int{4}
}

func (m *CredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialRequest.Unmarshal(m, b)
}
func (m *CredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialRequest.Marshal(b, m, deterministic)
}
func (m *CredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialRequest.Merge(m, src)
}
func (m *CredentialRequest) XXX_Size() int {
	return xxx_messageInfo_CredentialRequest.Size(m)
}
func (m *CredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialRequest proto.InternalMessageInfo

func (m *CredentialRequest) GetClientAddress() []byte {
	if m != nil {
		return m.ClientAddress
	}
	return nil
}

func (m *CredentialRequest) GetPipeAccountAddress() []byte {
	if m != nil {
		return m.PipeAccountAddress
	}
	return nil
}

func (m *CredentialRequest) GetCryptoMaterials() *scheme.ProtoBlindSignMaterials {
	if m != nil {
		return m.CryptoMaterials
	}
	return nil
}

func (m *CredentialRequest) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *CredentialRequest) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *CredentialRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func init() {
	proto.RegisterType((*NewAccountRequest)(nil), "transaction.NewAccountRequest")
	proto.RegisterType((*AccountTransferRequest)(nil), "transaction.AccountTransferRequest")
	proto.RegisterType((*DepositCoconutCredentialRequest)(nil), "transaction.DepositCoconutCredentialRequest")
	proto.RegisterType((*TransferToPipeAccountNotification)(nil), "transaction.TransferToPipeAccountNotification")
	proto.RegisterType((*CredentialRequest)(nil), "transaction.CredentialRequest")
}

func init() {
	proto.RegisterFile("tendermint/nymabci/transaction/proto/types.proto", fileDescriptor_ffb862c5130efc92)
}

var fileDescriptor_ffb862c5130efc92 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0x56, 0xd6, 0x26, 0x93, 0xbc, 0x4d, 0xdd, 0xac, 0x9f, 0xfa, 0x8b, 0x7a, 0x01, 0xa5, 0x42,
	0xa2, 0x70, 0x91, 0x4c, 0x43, 0x88, 0xeb, 0xae, 0x5c, 0x20, 0x50, 0xab, 0x2a, 0x8d, 0x40, 0xe2,
	0x06, 0x39, 0xce, 0x59, 0x63, 0x29, 0xb1, 0x83, 0xe3, 0x6c, 0xf4, 0x7d, 0x78, 0x22, 0x5e, 0x82,
	0x07, 0xe0, 0x05, 0x90, 0x9d, 0xa4, 0x4d, 0x56, 0x36, 0x71, 0x95, 0x9c, 0x7f, 0xfe, 0xbe, 0x73,
	0xbe, 0x63, 0xa3, 0x4b, 0x05, 0x3c, 0x06, 0x99, 0x31, 0xae, 0x7c, 0xbe, 0xcd, 0x48, 0x44, 0x99,
	0xaf, 0x24, 0xe1, 0x05, 0xa1, 0x8a, 0x09, 0xee, 0xe7, 0x52, 0x28, 0xe1, 0xab, 0x6d, 0x0e, 0x85,
	0x67, 0xfe, 0xf1, 0x49, 0x2b, 0x3c, 0x7a, 0x41, 0xe5, 0x36, 0x57, 0xc2, 0xa7, 0x82, 0x0a, 0x5e,
	0x2a, 0xbf, 0xa0, 0x09, 0x64, 0x70, 0x58, 0x35, 0xf2, 0x1e, 0x4d, 0x2c, 0xb3, 0x28, 0x05, 0xd9,
	0xca, 0x9f, 0x7c, 0x45, 0x17, 0x4b, 0xb8, 0x9b, 0x51, 0x2a, 0x4a, 0xae, 0x02, 0xf8, 0x56, 0x42,
	0xa1, 0xb0, 0x8b, 0x8e, 0x67, 0x71, 0x2c, 0xa1, 0x28, 0x5c, 0x6b, 0x6c, 0x4d, 0x4f, 0x83, 0x63,
	0x52, 0x99, 0xf8, 0x09, 0x42, 0x73, 0x09, 0x31, 0x70, 0xc5, 0x48, 0xea, 0x1e, 0x99, 0x20, 0xa2,
	0x3b, 0x0f, 0x3e, 0x47, 0xbd, 0x35, 0xdb, 0xb8, 0x3d, 0x13, 0xe8, 0x15, 0x6c, 0x33, 0xf9, 0x61,
	0xa1, 0x61, 0x7d, 0x7c, 0xa8, 0x1b, 0xba, 0x01, 0xd9, 0xc0, 0x3c, 0x47, 0x67, 0x6b, 0x51, 0x4a,
	0x0a, 0x5d, 0xb0, 0xb3, 0xa2, 0xed, 0xd4, 0x59, 0x21, 0x91, 0x1b, 0x50, 0x4d, 0x56, 0x85, 0x7a,
	0xa6, 0xda, 0x4e, 0x3c, 0x44, 0xce, 0x2c, 0xd3, 0x20, 0x06, 0xbb, 0x1f, 0x38, 0xc4, 0x58, 0xf8,
	0x3f, 0x64, 0x2f, 0x05, 0xa7, 0xe0, 0xf6, 0x4d, 0x95, 0xcd, 0xb5, 0xd1, 0xd0, 0xb4, 0xf7, 0x34,
	0x7f, 0x5a, 0xe8, 0xe9, 0x3b, 0xc8, 0x45, 0xc1, 0xd4, 0xbc, 0x1a, 0xdd, 0xbe, 0xcf, 0x86, 0xef,
	0xcb, 0xaa, 0x4a, 0xb3, 0x3c, 0xb9, 0xfa, 0xdf, 0xab, 0x47, 0xec, 0xad, 0xf4, 0x20, 0xd7, 0x6c,
	0xc3, 0x89, 0x2a, 0x25, 0x98, 0xe3, 0x30, 0x46, 0xfd, 0x55, 0x19, 0x2d, 0xdc, 0xa3, 0x71, 0x6f,
	0x7a, 0x1a, 0xf4, 0xf3, 0x32, 0x5a, 0xe0, 0x4b, 0x64, 0x87, 0x09, 0x28, 0x62, 0x18, 0x9e, 0x5c,
	0x8d, 0xba, 0x07, 0x98, 0x50, 0x58, 0x09, 0x14, 0xd8, 0x4a, 0x5b, 0x9a, 0xfc, 0x27, 0x92, 0x96,
	0x15, 0xf9, 0x5e, 0x60, 0xdf, 0x6a, 0x03, 0x4f, 0xd1, 0x60, 0x25, 0xc5, 0x2d, 0x8b, 0x41, 0x36,
	0x23, 0xa9, 0x1a, 0x19, 0xe4, 0x5d, 0xf7, 0xe4, 0x97, 0x85, 0x9e, 0x35, 0x43, 0x0f, 0xc5, 0x8a,
	0xe5, 0x50, 0x2b, 0xb1, 0x14, 0x8a, 0xdd, 0x30, 0x4a, 0xf4, 0x6e, 0xe1, 0x57, 0xe8, 0xfc, 0x33,
	0x51, 0x34, 0x01, 0xb9, 0x2a, 0xa3, 0x94, 0xd1, 0x8f, 0xb0, 0xad, 0x95, 0x38, 0xbf, 0xbb, 0xe7,
	0xd7, 0x62, 0xcc, 0x53, 0x06, 0xfc, 0xbe, 0x18, 0xb4, 0xed, 0xc4, 0x1e, 0xc2, 0x2d, 0xb0, 0x26,
	0xb5, 0x5a, 0x0a, 0x9c, 0x1f, 0x44, 0x5a, 0xe2, 0xf5, 0x3b, 0xe2, 0x0d, 0x91, 0x13, 0x7e, 0x7f,
	0x4f, 0x8a, 0xa4, 0x6e, 0xd0, 0x51, 0xc6, 0x6a, 0xe4, 0x73, 0xf6, 0xf2, 0xfd, 0xb6, 0xd0, 0xc5,
	0xa1, 0x60, 0x07, 0x6c, 0xad, 0x7f, 0x67, 0x7b, 0xf4, 0x20, 0xdb, 0x0f, 0x68, 0x30, 0x37, 0x97,
	0x6c, 0x41, 0x14, 0x48, 0x46, 0xd2, 0xa2, 0x56, 0x74, 0xdc, 0x55, 0xf4, 0x3a, 0x65, 0x3c, 0xd6,
	0x7b, 0xb1, 0xcb, 0x0b, 0x06, 0xb4, 0x5b, 0xf8, 0x80, 0xc2, 0xbb, 0xa5, 0xb5, 0xff, 0xb2, 0xb4,
	0xfb, 0xae, 0xaf, 0xdf, 0x7e, 0x79, 0xb3, 0x61, 0x2a, 0x29, 0x23, 0x8f, 0x8a, 0x4c, 0x3f, 0x2b,
	0x0a, 0x68, 0xa2, 0xbf, 0xfe, 0xe3, 0xaf, 0x4d, 0xe4, 0x98, 0xcb, 0xff, 0xfa, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x08, 0x50, 0xfa, 0x4d, 0x96, 0x04, 0x00, 0x00,
}
