// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/comm/commands/proto/types.proto

package commands

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	scheme "github.com/nymtech/nym/crypto/coconut/scheme"
	elgamal "github.com/nymtech/nym/crypto/elgamal"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_OK                      StatusCode = 0
	StatusCode_UNKNOWN                 StatusCode = 1
	StatusCode_INVALID_COMMAND         StatusCode = 2
	StatusCode_INVALID_ARGUMENTS       StatusCode = 3
	StatusCode_PROCESSING_ERROR        StatusCode = 4
	StatusCode_NOT_IMPLEMENTED         StatusCode = 5
	StatusCode_REQUEST_TIMEOUT         StatusCode = 6
	StatusCode_UNAVAILABLE             StatusCode = 7
	StatusCode_INVALID_TRANSACTION     StatusCode = 8
	StatusCode_INVALID_BINDING         StatusCode = 9
	StatusCode_INVALID_SIGNATURE       StatusCode = 10
	StatusCode_TX_NOT_ON_CHAIN         StatusCode = 11
	StatusCode_NOT_PROCESSED_YET       StatusCode = 12
	StatusCode_DOUBLE_SPENDING_ATTEMPT StatusCode = 13
)

var StatusCode_name = map[int32]string{
	0:  "OK",
	1:  "UNKNOWN",
	2:  "INVALID_COMMAND",
	3:  "INVALID_ARGUMENTS",
	4:  "PROCESSING_ERROR",
	5:  "NOT_IMPLEMENTED",
	6:  "REQUEST_TIMEOUT",
	7:  "UNAVAILABLE",
	8:  "INVALID_TRANSACTION",
	9:  "INVALID_BINDING",
	10: "INVALID_SIGNATURE",
	11: "TX_NOT_ON_CHAIN",
	12: "NOT_PROCESSED_YET",
	13: "DOUBLE_SPENDING_ATTEMPT",
}

var StatusCode_value = map[string]int32{
	"OK":                      0,
	"UNKNOWN":                 1,
	"INVALID_COMMAND":         2,
	"INVALID_ARGUMENTS":       3,
	"PROCESSING_ERROR":        4,
	"NOT_IMPLEMENTED":         5,
	"REQUEST_TIMEOUT":         6,
	"UNAVAILABLE":             7,
	"INVALID_TRANSACTION":     8,
	"INVALID_BINDING":         9,
	"INVALID_SIGNATURE":       10,
	"TX_NOT_ON_CHAIN":         11,
	"NOT_PROCESSED_YET":       12,
	"DOUBLE_SPENDING_ATTEMPT": 13,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{0}
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SignRequest struct {
	PubM                 [][]byte `protobuf:"bytes,1,rep,name=pubM,proto3" json:"pubM,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRequest) Reset()         { *m = SignRequest{} }
func (m *SignRequest) String() string { return proto.CompactTextString(m) }
func (*SignRequest) ProtoMessage()    {}
func (*SignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{1}
}

func (m *SignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRequest.Unmarshal(m, b)
}
func (m *SignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRequest.Marshal(b, m, deterministic)
}
func (m *SignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRequest.Merge(m, src)
}
func (m *SignRequest) XXX_Size() int {
	return xxx_messageInfo_SignRequest.Size(m)
}
func (m *SignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignRequest proto.InternalMessageInfo

func (m *SignRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

type SignResponse struct {
	Sig                  *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	IssuerID             int64                  `protobuf:"varint,2,opt,name=IssuerID,json=issuerID,proto3" json:"IssuerID,omitempty"`
	Status               *Status                `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SignResponse) Reset()         { *m = SignResponse{} }
func (m *SignResponse) String() string { return proto.CompactTextString(m) }
func (*SignResponse) ProtoMessage()    {}
func (*SignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{2}
}

func (m *SignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignResponse.Unmarshal(m, b)
}
func (m *SignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignResponse.Marshal(b, m, deterministic)
}
func (m *SignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignResponse.Merge(m, src)
}
func (m *SignResponse) XXX_Size() int {
	return xxx_messageInfo_SignResponse.Size(m)
}
func (m *SignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignResponse proto.InternalMessageInfo

func (m *SignResponse) GetSig() *scheme.ProtoSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *SignResponse) GetIssuerID() int64 {
	if m != nil {
		return m.IssuerID
	}
	return 0
}

func (m *SignResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type VerificationKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerificationKeyRequest) Reset()         { *m = VerificationKeyRequest{} }
func (m *VerificationKeyRequest) String() string { return proto.CompactTextString(m) }
func (*VerificationKeyRequest) ProtoMessage()    {}
func (*VerificationKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{3}
}

func (m *VerificationKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationKeyRequest.Unmarshal(m, b)
}
func (m *VerificationKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationKeyRequest.Marshal(b, m, deterministic)
}
func (m *VerificationKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationKeyRequest.Merge(m, src)
}
func (m *VerificationKeyRequest) XXX_Size() int {
	return xxx_messageInfo_VerificationKeyRequest.Size(m)
}
func (m *VerificationKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationKeyRequest proto.InternalMessageInfo

type VerificationKeyResponse struct {
	Vk                   *scheme.ProtoVerificationKey `protobuf:"bytes,1,opt,name=vk,proto3" json:"vk,omitempty"`
	IssuerID             int64                        `protobuf:"varint,2,opt,name=IssuerID,json=issuerID,proto3" json:"IssuerID,omitempty"`
	Status               *Status                      `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *VerificationKeyResponse) Reset()         { *m = VerificationKeyResponse{} }
func (m *VerificationKeyResponse) String() string { return proto.CompactTextString(m) }
func (*VerificationKeyResponse) ProtoMessage()    {}
func (*VerificationKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{4}
}

func (m *VerificationKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationKeyResponse.Unmarshal(m, b)
}
func (m *VerificationKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationKeyResponse.Marshal(b, m, deterministic)
}
func (m *VerificationKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationKeyResponse.Merge(m, src)
}
func (m *VerificationKeyResponse) XXX_Size() int {
	return xxx_messageInfo_VerificationKeyResponse.Size(m)
}
func (m *VerificationKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationKeyResponse proto.InternalMessageInfo

func (m *VerificationKeyResponse) GetVk() *scheme.ProtoVerificationKey {
	if m != nil {
		return m.Vk
	}
	return nil
}

func (m *VerificationKeyResponse) GetIssuerID() int64 {
	if m != nil {
		return m.IssuerID
	}
	return 0
}

func (m *VerificationKeyResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type VerifyRequest struct {
	Sig                  *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	PubM                 [][]byte               `protobuf:"bytes,2,rep,name=pubM,proto3" json:"pubM,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{5}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetSig() *scheme.ProtoSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *VerifyRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

type VerifyResponse struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{6}
}

func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (m *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(m, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

func (m *VerifyResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *VerifyResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type BlindSignRequest struct {
	PubM                 [][]byte                `protobuf:"bytes,1,rep,name=pubM,proto3" json:"pubM,omitempty"`
	Lambda               *scheme.ProtoLambda     `protobuf:"bytes,2,opt,name=lambda,proto3" json:"lambda,omitempty"`
	EgPub                *elgamal.ProtoPublicKey `protobuf:"bytes,3,opt,name=egPub,proto3" json:"egPub,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BlindSignRequest) Reset()         { *m = BlindSignRequest{} }
func (m *BlindSignRequest) String() string { return proto.CompactTextString(m) }
func (*BlindSignRequest) ProtoMessage()    {}
func (*BlindSignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{7}
}

func (m *BlindSignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlindSignRequest.Unmarshal(m, b)
}
func (m *BlindSignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlindSignRequest.Marshal(b, m, deterministic)
}
func (m *BlindSignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlindSignRequest.Merge(m, src)
}
func (m *BlindSignRequest) XXX_Size() int {
	return xxx_messageInfo_BlindSignRequest.Size(m)
}
func (m *BlindSignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlindSignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlindSignRequest proto.InternalMessageInfo

func (m *BlindSignRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

func (m *BlindSignRequest) GetLambda() *scheme.ProtoLambda {
	if m != nil {
		return m.Lambda
	}
	return nil
}

func (m *BlindSignRequest) GetEgPub() *elgamal.ProtoPublicKey {
	if m != nil {
		return m.EgPub
	}
	return nil
}

type BlindSignResponse struct {
	Sig                  *scheme.ProtoBlindedSignature `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	IssuerID             int64                         `protobuf:"varint,2,opt,name=IssuerID,json=issuerID,proto3" json:"IssuerID,omitempty"`
	Status               *Status                       `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *BlindSignResponse) Reset()         { *m = BlindSignResponse{} }
func (m *BlindSignResponse) String() string { return proto.CompactTextString(m) }
func (*BlindSignResponse) ProtoMessage()    {}
func (*BlindSignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{8}
}

func (m *BlindSignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlindSignResponse.Unmarshal(m, b)
}
func (m *BlindSignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlindSignResponse.Marshal(b, m, deterministic)
}
func (m *BlindSignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlindSignResponse.Merge(m, src)
}
func (m *BlindSignResponse) XXX_Size() int {
	return xxx_messageInfo_BlindSignResponse.Size(m)
}
func (m *BlindSignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlindSignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlindSignResponse proto.InternalMessageInfo

func (m *BlindSignResponse) GetSig() *scheme.ProtoBlindedSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *BlindSignResponse) GetIssuerID() int64 {
	if m != nil {
		return m.IssuerID
	}
	return 0
}

func (m *BlindSignResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type BlindVerifyRequest struct {
	Sig                  *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	PubM                 [][]byte               `protobuf:"bytes,2,rep,name=pubM,proto3" json:"pubM,omitempty"`
	Theta                *scheme.ProtoTheta     `protobuf:"bytes,3,opt,name=theta,proto3" json:"theta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BlindVerifyRequest) Reset()         { *m = BlindVerifyRequest{} }
func (m *BlindVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*BlindVerifyRequest) ProtoMessage()    {}
func (*BlindVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{9}
}

func (m *BlindVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlindVerifyRequest.Unmarshal(m, b)
}
func (m *BlindVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlindVerifyRequest.Marshal(b, m, deterministic)
}
func (m *BlindVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlindVerifyRequest.Merge(m, src)
}
func (m *BlindVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_BlindVerifyRequest.Size(m)
}
func (m *BlindVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlindVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlindVerifyRequest proto.InternalMessageInfo

func (m *BlindVerifyRequest) GetSig() *scheme.ProtoSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *BlindVerifyRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

func (m *BlindVerifyRequest) GetTheta() *scheme.ProtoTheta {
	if m != nil {
		return m.Theta
	}
	return nil
}

type BlindVerifyResponse struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlindVerifyResponse) Reset()         { *m = BlindVerifyResponse{} }
func (m *BlindVerifyResponse) String() string { return proto.CompactTextString(m) }
func (*BlindVerifyResponse) ProtoMessage()    {}
func (*BlindVerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{10}
}

func (m *BlindVerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlindVerifyResponse.Unmarshal(m, b)
}
func (m *BlindVerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlindVerifyResponse.Marshal(b, m, deterministic)
}
func (m *BlindVerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlindVerifyResponse.Merge(m, src)
}
func (m *BlindVerifyResponse) XXX_Size() int {
	return xxx_messageInfo_BlindVerifyResponse.Size(m)
}
func (m *BlindVerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlindVerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlindVerifyResponse proto.InternalMessageInfo

func (m *BlindVerifyResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *BlindVerifyResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// Sent by user to some service provider
type SpendCredentialRequest struct {
	// The actual credential
	Sig *scheme.ProtoSignature `protobuf:"bytes,1,opt,name=Sig,json=sig,proto3" json:"Sig,omitempty"`
	// The public attributes in credential. Note that pubM[0] = BIG(value)
	PubM [][]byte `protobuf:"bytes,2,rep,name=PubM,json=pubM,proto3" json:"PubM,omitempty"`
	// Crypto materials to verify the credential + required NIZK; also contains g^s
	Theta *scheme.ProtoThetaTumbler `protobuf:"bytes,3,opt,name=Theta,json=theta,proto3" json:"Theta,omitempty"`
	// Value of the credential
	Value int64 `protobuf:"varint,4,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	// Address of the merchant to which the proof is bound. Included so that the provider could verify it
	MerchantAddress      []byte   `protobuf:"bytes,5,opt,name=MerchantAddress,json=merchantAddress,proto3" json:"MerchantAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpendCredentialRequest) Reset()         { *m = SpendCredentialRequest{} }
func (m *SpendCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*SpendCredentialRequest) ProtoMessage()    {}
func (*SpendCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{11}
}

func (m *SpendCredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpendCredentialRequest.Unmarshal(m, b)
}
func (m *SpendCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpendCredentialRequest.Marshal(b, m, deterministic)
}
func (m *SpendCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpendCredentialRequest.Merge(m, src)
}
func (m *SpendCredentialRequest) XXX_Size() int {
	return xxx_messageInfo_SpendCredentialRequest.Size(m)
}
func (m *SpendCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpendCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpendCredentialRequest proto.InternalMessageInfo

func (m *SpendCredentialRequest) GetSig() *scheme.ProtoSignature {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *SpendCredentialRequest) GetPubM() [][]byte {
	if m != nil {
		return m.PubM
	}
	return nil
}

func (m *SpendCredentialRequest) GetTheta() *scheme.ProtoThetaTumbler {
	if m != nil {
		return m.Theta
	}
	return nil
}

func (m *SpendCredentialRequest) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *SpendCredentialRequest) GetMerchantAddress() []byte {
	if m != nil {
		return m.MerchantAddress
	}
	return nil
}

type SpendCredentialResponse struct {
	WasSuccessful        bool     `protobuf:"varint,1,opt,name=wasSuccessful,proto3" json:"wasSuccessful,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpendCredentialResponse) Reset()         { *m = SpendCredentialResponse{} }
func (m *SpendCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*SpendCredentialResponse) ProtoMessage()    {}
func (*SpendCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{12}
}

func (m *SpendCredentialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpendCredentialResponse.Unmarshal(m, b)
}
func (m *SpendCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpendCredentialResponse.Marshal(b, m, deterministic)
}
func (m *SpendCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpendCredentialResponse.Merge(m, src)
}
func (m *SpendCredentialResponse) XXX_Size() int {
	return xxx_messageInfo_SpendCredentialResponse.Size(m)
}
func (m *SpendCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SpendCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SpendCredentialResponse proto.InternalMessageInfo

func (m *SpendCredentialResponse) GetWasSuccessful() bool {
	if m != nil {
		return m.WasSuccessful
	}
	return false
}

func (m *SpendCredentialResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type IssuedCredential struct {
	// sig is defined as bytes rather than protoBlindedSignature as it in fact is marshalled proto blinded signature
	// there is no point in extra unmarshaling and further marshaling just for the sake of it.
	Sig                  []byte   `protobuf:"bytes,1,opt,name=Sig,json=sig,proto3" json:"Sig,omitempty"`
	IssuerID             int64    `protobuf:"varint,2,opt,name=IssuerID,json=issuerID,proto3" json:"IssuerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssuedCredential) Reset()         { *m = IssuedCredential{} }
func (m *IssuedCredential) String() string { return proto.CompactTextString(m) }
func (*IssuedCredential) ProtoMessage()    {}
func (*IssuedCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{13}
}

func (m *IssuedCredential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuedCredential.Unmarshal(m, b)
}
func (m *IssuedCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuedCredential.Marshal(b, m, deterministic)
}
func (m *IssuedCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuedCredential.Merge(m, src)
}
func (m *IssuedCredential) XXX_Size() int {
	return xxx_messageInfo_IssuedCredential.Size(m)
}
func (m *IssuedCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuedCredential.DiscardUnknown(m)
}

var xxx_messageInfo_IssuedCredential proto.InternalMessageInfo

func (m *IssuedCredential) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *IssuedCredential) GetIssuerID() int64 {
	if m != nil {
		return m.IssuerID
	}
	return 0
}

// defines blinded credential and gamma to which it was issued
// unless client reused gamma which they shouldn't have, it will be identical to what they sent before,
// otherwise it will have additional suffix to indicate a duplicate (in given block)
type CredentialPair struct {
	Gamma                []byte            `protobuf:"bytes,1,opt,name=gamma,proto3" json:"gamma,omitempty"`
	Credential           *IssuedCredential `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CredentialPair) Reset()         { *m = CredentialPair{} }
func (m *CredentialPair) String() string { return proto.CompactTextString(m) }
func (*CredentialPair) ProtoMessage()    {}
func (*CredentialPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{14}
}

func (m *CredentialPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialPair.Unmarshal(m, b)
}
func (m *CredentialPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialPair.Marshal(b, m, deterministic)
}
func (m *CredentialPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialPair.Merge(m, src)
}
func (m *CredentialPair) XXX_Size() int {
	return xxx_messageInfo_CredentialPair.Size(m)
}
func (m *CredentialPair) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialPair.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialPair proto.InternalMessageInfo

func (m *CredentialPair) GetGamma() []byte {
	if m != nil {
		return m.Gamma
	}
	return nil
}

func (m *CredentialPair) GetCredential() *IssuedCredential {
	if m != nil {
		return m.Credential
	}
	return nil
}

type LookUpCredentialRequest struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Gamma                []byte   `protobuf:"bytes,2,opt,name=gamma,proto3" json:"gamma,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookUpCredentialRequest) Reset()         { *m = LookUpCredentialRequest{} }
func (m *LookUpCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*LookUpCredentialRequest) ProtoMessage()    {}
func (*LookUpCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{15}
}

func (m *LookUpCredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpCredentialRequest.Unmarshal(m, b)
}
func (m *LookUpCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpCredentialRequest.Marshal(b, m, deterministic)
}
func (m *LookUpCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpCredentialRequest.Merge(m, src)
}
func (m *LookUpCredentialRequest) XXX_Size() int {
	return xxx_messageInfo_LookUpCredentialRequest.Size(m)
}
func (m *LookUpCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpCredentialRequest proto.InternalMessageInfo

func (m *LookUpCredentialRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *LookUpCredentialRequest) GetGamma() []byte {
	if m != nil {
		return m.Gamma
	}
	return nil
}

type LookUpCredentialResponse struct {
	CredentialPair       *CredentialPair `protobuf:"bytes,1,opt,name=credentialPair,proto3" json:"credentialPair,omitempty"`
	Status               *Status         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LookUpCredentialResponse) Reset()         { *m = LookUpCredentialResponse{} }
func (m *LookUpCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*LookUpCredentialResponse) ProtoMessage()    {}
func (*LookUpCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{16}
}

func (m *LookUpCredentialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpCredentialResponse.Unmarshal(m, b)
}
func (m *LookUpCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpCredentialResponse.Marshal(b, m, deterministic)
}
func (m *LookUpCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpCredentialResponse.Merge(m, src)
}
func (m *LookUpCredentialResponse) XXX_Size() int {
	return xxx_messageInfo_LookUpCredentialResponse.Size(m)
}
func (m *LookUpCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpCredentialResponse proto.InternalMessageInfo

func (m *LookUpCredentialResponse) GetCredentialPair() *CredentialPair {
	if m != nil {
		return m.CredentialPair
	}
	return nil
}

func (m *LookUpCredentialResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type LookUpBlockCredentialsRequest struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookUpBlockCredentialsRequest) Reset()         { *m = LookUpBlockCredentialsRequest{} }
func (m *LookUpBlockCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*LookUpBlockCredentialsRequest) ProtoMessage()    {}
func (*LookUpBlockCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{17}
}

func (m *LookUpBlockCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpBlockCredentialsRequest.Unmarshal(m, b)
}
func (m *LookUpBlockCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpBlockCredentialsRequest.Marshal(b, m, deterministic)
}
func (m *LookUpBlockCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpBlockCredentialsRequest.Merge(m, src)
}
func (m *LookUpBlockCredentialsRequest) XXX_Size() int {
	return xxx_messageInfo_LookUpBlockCredentialsRequest.Size(m)
}
func (m *LookUpBlockCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpBlockCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpBlockCredentialsRequest proto.InternalMessageInfo

func (m *LookUpBlockCredentialsRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type LookUpBlockCredentialsResponse struct {
	Credentials          []*CredentialPair `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	Status               *Status           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LookUpBlockCredentialsResponse) Reset()         { *m = LookUpBlockCredentialsResponse{} }
func (m *LookUpBlockCredentialsResponse) String() string { return proto.CompactTextString(m) }
func (*LookUpBlockCredentialsResponse) ProtoMessage()    {}
func (*LookUpBlockCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a06cb57e68cc23, []int{18}
}

func (m *LookUpBlockCredentialsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpBlockCredentialsResponse.Unmarshal(m, b)
}
func (m *LookUpBlockCredentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpBlockCredentialsResponse.Marshal(b, m, deterministic)
}
func (m *LookUpBlockCredentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpBlockCredentialsResponse.Merge(m, src)
}
func (m *LookUpBlockCredentialsResponse) XXX_Size() int {
	return xxx_messageInfo_LookUpBlockCredentialsResponse.Size(m)
}
func (m *LookUpBlockCredentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpBlockCredentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpBlockCredentialsResponse proto.InternalMessageInfo

func (m *LookUpBlockCredentialsResponse) GetCredentials() []*CredentialPair {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *LookUpBlockCredentialsResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("commands.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*Status)(nil), "commands.Status")
	proto.RegisterType((*SignRequest)(nil), "commands.SignRequest")
	proto.RegisterType((*SignResponse)(nil), "commands.SignResponse")
	proto.RegisterType((*VerificationKeyRequest)(nil), "commands.VerificationKeyRequest")
	proto.RegisterType((*VerificationKeyResponse)(nil), "commands.VerificationKeyResponse")
	proto.RegisterType((*VerifyRequest)(nil), "commands.VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "commands.VerifyResponse")
	proto.RegisterType((*BlindSignRequest)(nil), "commands.BlindSignRequest")
	proto.RegisterType((*BlindSignResponse)(nil), "commands.BlindSignResponse")
	proto.RegisterType((*BlindVerifyRequest)(nil), "commands.BlindVerifyRequest")
	proto.RegisterType((*BlindVerifyResponse)(nil), "commands.BlindVerifyResponse")
	proto.RegisterType((*SpendCredentialRequest)(nil), "commands.SpendCredentialRequest")
	proto.RegisterType((*SpendCredentialResponse)(nil), "commands.SpendCredentialResponse")
	proto.RegisterType((*IssuedCredential)(nil), "commands.issuedCredential")
	proto.RegisterType((*CredentialPair)(nil), "commands.credentialPair")
	proto.RegisterType((*LookUpCredentialRequest)(nil), "commands.LookUpCredentialRequest")
	proto.RegisterType((*LookUpCredentialResponse)(nil), "commands.LookUpCredentialResponse")
	proto.RegisterType((*LookUpBlockCredentialsRequest)(nil), "commands.LookUpBlockCredentialsRequest")
	proto.RegisterType((*LookUpBlockCredentialsResponse)(nil), "commands.LookUpBlockCredentialsResponse")
}

func init() {
	proto.RegisterFile("common/comm/commands/proto/types.proto", fileDescriptor_c9a06cb57e68cc23)
}

var fileDescriptor_c9a06cb57e68cc23 = []byte{
	// 944 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0xe2, 0x46,
	0x18, 0xad, 0x21, 0x90, 0xec, 0x07, 0xd9, 0x78, 0x27, 0x69, 0xb0, 0xa8, 0x76, 0x45, 0xad, 0xaa,
	0x65, 0xdb, 0x06, 0x56, 0xad, 0xd4, 0x4a, 0x7b, 0xb5, 0x06, 0x2c, 0x6a, 0x05, 0x6c, 0x3a, 0x36,
	0xb4, 0xdb, 0x1b, 0x64, 0xec, 0x59, 0xb0, 0xe2, 0x1f, 0xea, 0xb1, 0x53, 0xe5, 0xa6, 0xbd, 0xa8,
	0xd4, 0x9b, 0x4a, 0x7d, 0x92, 0xbe, 0x48, 0xdf, 0xaa, 0x1a, 0x33, 0x14, 0x03, 0xe9, 0x26, 0x2b,
	0x65, 0x6f, 0xf0, 0xcc, 0x7c, 0x67, 0xce, 0x77, 0xce, 0x99, 0x91, 0x31, 0x7c, 0xea, 0x44, 0x41,
	0x10, 0x85, 0x6d, 0xf6, 0xc8, 0x7e, 0xec, 0xd0, 0xa5, 0xed, 0x65, 0x1c, 0x25, 0x51, 0x3b, 0xb9,
	0x59, 0x12, 0xda, 0xca, 0xc6, 0xe8, 0x68, 0x5d, 0xab, 0x7f, 0xe6, 0xc4, 0x37, 0xcb, 0x24, 0x6a,
	0x3b, 0x91, 0x13, 0x85, 0x69, 0xd2, 0xa6, 0xce, 0x82, 0x04, 0x64, 0x7f, 0x4b, 0xbd, 0xc1, 0x81,
	0xc4, 0x9f, 0xdb, 0x81, 0xed, 0xdf, 0x82, 0x68, 0xbd, 0x95, 0x2a, 0x0d, 0x66, 0x3e, 0x89, 0x73,
	0x78, 0xf9, 0x1b, 0x28, 0x9b, 0x89, 0x9d, 0xa4, 0x14, 0x21, 0x38, 0x70, 0x22, 0x97, 0x48, 0x42,
	0x43, 0x68, 0x96, 0x70, 0x36, 0x46, 0x12, 0x1c, 0x06, 0x84, 0x52, 0x7b, 0x4e, 0xa4, 0x42, 0x43,
	0x68, 0x3e, 0xc2, 0xeb, 0xa9, 0xfc, 0x31, 0x54, 0x4c, 0x6f, 0x1e, 0x62, 0xf2, 0x73, 0x4a, 0x68,
	0xc2, 0x36, 0x2f, 0xd3, 0xd9, 0x50, 0x12, 0x1a, 0xc5, 0x66, 0x15, 0x67, 0x63, 0xf9, 0x37, 0xa8,
	0xae, 0x20, 0x74, 0x19, 0x85, 0x94, 0xa0, 0xe7, 0x50, 0xa4, 0xde, 0x3c, 0xe3, 0xaf, 0x7c, 0x55,
	0x6b, 0x71, 0x85, 0xad, 0x11, 0xd3, 0xc1, 0x80, 0x76, 0x92, 0xc6, 0x04, 0x33, 0x0c, 0xaa, 0xc3,
	0x91, 0x46, 0x69, 0x4a, 0x62, 0xad, 0x97, 0x35, 0x2e, 0xe2, 0x23, 0x8f, 0xcf, 0x51, 0x13, 0xca,
	0x34, 0x53, 0x2c, 0x15, 0x33, 0x26, 0xb1, 0xb5, 0xce, 0xb1, 0xb5, 0x72, 0x82, 0x79, 0x5d, 0x96,
	0xe0, 0x7c, 0x42, 0x62, 0xef, 0x8d, 0xe7, 0xd8, 0x89, 0x17, 0x85, 0x97, 0xe4, 0x86, 0xcb, 0x95,
	0xff, 0x12, 0xa0, 0xb6, 0x57, 0xe2, 0x32, 0x2f, 0xa0, 0x70, 0x7d, 0xc5, 0x55, 0x3e, 0xdd, 0x56,
	0xb9, 0xbb, 0xa5, 0x70, 0x7d, 0xf5, 0x40, 0x52, 0x75, 0x38, 0xce, 0xc8, 0xd7, 0x0a, 0xdf, 0x25,
	0xac, 0x75, 0xf6, 0x85, 0x5c, 0xf6, 0x16, 0x3c, 0x5e, 0xf3, 0x71, 0x5b, 0x12, 0x1c, 0x7a, 0x74,
	0x62, 0xfb, 0x9e, 0x9b, 0x91, 0x1e, 0xe1, 0xf5, 0x34, 0xa7, 0xb2, 0x70, 0x87, 0xca, 0xdf, 0x05,
	0x10, 0x3b, 0xbe, 0x17, 0xba, 0x77, 0x1c, 0x3d, 0xfa, 0x12, 0xca, 0xbe, 0x1d, 0xcc, 0x5c, 0x9b,
	0x53, 0x9e, 0x6d, 0x1b, 0x18, 0x64, 0x35, 0xcc, 0x31, 0xe8, 0x02, 0x4a, 0x64, 0x3e, 0x4a, 0x67,
	0x3c, 0xa5, 0x5a, 0x8b, 0x5f, 0xef, 0x15, 0x78, 0x94, 0xce, 0x7c, 0xcf, 0x61, 0x71, 0xaf, 0x50,
	0xf2, 0x9f, 0x02, 0x3c, 0xc9, 0xa9, 0xe0, 0xfe, 0x5e, 0xe4, 0x03, 0x7b, 0xb6, 0xdd, 0x2f, 0x43,
	0x13, 0xf7, 0xbd, 0x5c, 0xb2, 0x5f, 0x01, 0x65, 0xf4, 0x0f, 0x79, 0x7c, 0xe8, 0x39, 0x94, 0x92,
	0x05, 0x49, 0x6c, 0xde, 0xfd, 0x74, 0x9b, 0xc0, 0x62, 0x25, 0xbc, 0x42, 0xc8, 0xaf, 0xe1, 0x74,
	0xab, 0xff, 0x03, 0x1e, 0xf7, 0x3f, 0x02, 0x9c, 0x9b, 0x4b, 0x12, 0xba, 0xdd, 0x98, 0xb8, 0x24,
	0x4c, 0x3c, 0xdb, 0xcf, 0xf9, 0x33, 0xef, 0xef, 0x6f, 0xb4, 0xeb, 0xef, 0x05, 0x94, 0xac, 0x9c,
	0xbf, 0xfa, 0x2d, 0xfe, 0xac, 0xd5, 0xbb, 0x8a, 0xdb, 0x44, 0x67, 0x50, 0x9a, 0xd8, 0x7e, 0x4a,
	0xa4, 0x83, 0xec, 0xa4, 0x4a, 0xd7, 0x6c, 0x82, 0x9a, 0x70, 0x32, 0x24, 0xb1, 0xb3, 0xb0, 0xc3,
	0x44, 0x71, 0xdd, 0x98, 0x50, 0x2a, 0x95, 0x1a, 0x42, 0xb3, 0x8a, 0x4f, 0x82, 0xed, 0x65, 0xd9,
	0x83, 0xda, 0x9e, 0x15, 0x1e, 0xd5, 0x27, 0x70, 0xfc, 0x8b, 0x4d, 0xcd, 0xd4, 0x71, 0x08, 0xa5,
	0x6f, 0x52, 0x9f, 0x07, 0xb6, 0xbd, 0xf8, 0x0e, 0xb1, 0xbd, 0x02, 0x31, 0xbb, 0x47, 0xb9, 0x5e,
	0x48, 0xdc, 0xe4, 0x55, 0xbd, 0xf3, 0xf6, 0xc9, 0x33, 0x78, 0xec, 0xfc, 0xb7, 0x77, 0x64, 0x7b,
	0x31, 0xb3, 0x3f, 0xb7, 0x83, 0xc0, 0xe6, 0x0c, 0xab, 0x09, 0x7a, 0x09, 0xb0, 0xc1, 0x71, 0x5d,
	0xf5, 0x8d, 0xae, 0x5d, 0x15, 0x38, 0x87, 0x96, 0xfb, 0x50, 0x1b, 0x44, 0xd1, 0xd5, 0x78, 0xb9,
	0x7f, 0xb8, 0xe7, 0x50, 0x5e, 0x10, 0x6f, 0xbe, 0x48, 0xb2, 0x6e, 0x45, 0xcc, 0x67, 0x1b, 0x11,
	0x85, 0x9c, 0x08, 0xf9, 0x0f, 0x01, 0xa4, 0x7d, 0x26, 0x9e, 0xed, 0xab, 0x5d, 0x27, 0xfc, 0xca,
	0x48, 0x1b, 0x95, 0xdb, 0x75, 0xbc, 0xeb, 0xfc, 0xfe, 0xb9, 0x7f, 0x0b, 0x4f, 0x57, 0x3a, 0x3a,
	0x7e, 0xe4, 0x5c, 0x6d, 0xc4, 0xd0, 0x3b, 0x7c, 0x31, 0x07, 0xcf, 0xfe, 0x6f, 0x27, 0xf7, 0xf1,
	0x12, 0x2a, 0x1b, 0x5d, 0x34, 0x7b, 0xd7, 0xbd, 0xcd, 0x44, 0x1e, 0x7c, 0x7f, 0x07, 0x9f, 0xff,
	0x5d, 0x00, 0x58, 0x2d, 0x75, 0xd9, 0xbf, 0x6f, 0x19, 0x0a, 0xc6, 0xa5, 0xf8, 0x01, 0xaa, 0xc0,
	0xe1, 0x58, 0xbf, 0xd4, 0x8d, 0x1f, 0x74, 0x51, 0x40, 0xa7, 0x70, 0xa2, 0xe9, 0x13, 0x65, 0xa0,
	0xf5, 0xa6, 0x5d, 0x63, 0x38, 0x54, 0xf4, 0x9e, 0x58, 0x40, 0x1f, 0xc2, 0x93, 0xf5, 0xa2, 0x82,
	0xfb, 0xe3, 0xa1, 0xaa, 0x5b, 0xa6, 0x58, 0x44, 0x67, 0x20, 0x8e, 0xb0, 0xd1, 0x55, 0x4d, 0x53,
	0xd3, 0xfb, 0x53, 0x15, 0x63, 0x03, 0x8b, 0x07, 0x8c, 0x41, 0x37, 0xac, 0xa9, 0x36, 0x1c, 0x0d,
	0x54, 0x86, 0x54, 0x7b, 0x62, 0x89, 0x2d, 0x62, 0xf5, 0xfb, 0xb1, 0x6a, 0x5a, 0x53, 0x4b, 0x1b,
	0xaa, 0xc6, 0xd8, 0x12, 0xcb, 0xe8, 0x04, 0x2a, 0x63, 0x5d, 0x99, 0x28, 0xda, 0x40, 0xe9, 0x0c,
	0x54, 0xf1, 0x10, 0xd5, 0xe0, 0x74, 0xdd, 0xc7, 0xc2, 0x8a, 0x6e, 0x2a, 0x5d, 0x4b, 0x33, 0x74,
	0xf1, 0x28, 0xaf, 0xaa, 0xa3, 0xe9, 0x3d, 0x4d, 0xef, 0x8b, 0x8f, 0xf2, 0xaa, 0x4c, 0xad, 0xaf,
	0x2b, 0xd6, 0x18, 0xab, 0x22, 0x30, 0xac, 0xf5, 0xe3, 0x94, 0x49, 0x30, 0xf4, 0x69, 0xf7, 0x3b,
	0x45, 0xd3, 0xc5, 0x0a, 0xc3, 0xb2, 0x15, 0x2e, 0x57, 0xed, 0x4d, 0x5f, 0xab, 0x96, 0x58, 0x45,
	0x1f, 0x41, 0xad, 0x67, 0x8c, 0x3b, 0x03, 0x75, 0x6a, 0x8e, 0xd4, 0x8c, 0x77, 0xaa, 0x58, 0x96,
	0x3a, 0x1c, 0x59, 0xe2, 0x71, 0xe7, 0xe2, 0xa7, 0x2f, 0xe6, 0x5e, 0xb2, 0x48, 0x67, 0x2c, 0xd0,
	0x76, 0x78, 0x13, 0x24, 0xc4, 0x59, 0xb0, 0x67, 0xfb, 0xb6, 0x2f, 0xb0, 0x59, 0x39, 0xfb, 0xe2,
	0xf9, 0xfa, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0xb9, 0x3b, 0x1d, 0xa0, 0x09, 0x00, 0x00,
}
